name: 'Self Service Catalog'
description: 'Find and catalog self service modules for Backstage'
author: 'Arron Nestor'

inputs:
  version:
    description: 'release tag'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'