apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-java-microservice-template
  title: Test Java Microservice Template
  description: Bootstrap application for Spring GraphQL microservices
  tags:
    - java
    - spring
    - graphql
  annotations:
    github.com/project-slug: triplelift-internal/microservice-templates
    backstage.io/techdocs-ref: dir:.
    backstage.io/code-coverage: enabled
spec:
  owner: auctions
  type: template
  lifecycle: experimental
  parameters:
    - title: Provide some simple information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component. Must be all lowercase and dash separated (i.e., "deals-api")
        description:
          title: Description
          type: string
          description: Help others understand what this service is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Select the dependencies you want
      required:
        - dependencies
      properties:
        dependencies:
          title: Available dependencies
          type: array
          default: []
          items:
            type: string
            enum:
              - sdk_publishing
              - flyway_migrate_files
            enumNames:
              - GraphQL Code Generator - This plugin generates graphql-request ready-to-use TypeScript SDK.
              - Flyway Migrate Files - Generate Flyway Migrate GitHub Actions and db-migrations folder with a sample file.
          ui:help: Select which dependencies you want include in your generated repository.
          ui:widget: checkboxes
          uniqueItems: true
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          default: github.com?owner=triplelift-internal&repo=
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Add Infrastructure
      properties:
        infrastructure:
          title: Infrastucture
          type: array
          default: [ ]
          ui:field: Infra

  steps:
    - id: fetch-repo
      name: Interpolating Values in Template
      action: fetch:template
      input:
        copyWithoutTemplating:
          - .github/workflows/draft-new-release.yml
          - .github/workflows/integration-tests.yml
          - .github/workflows/publish-release.yml
          - .github/workflows/unit-tests.yml
          - docs/themes/*
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          dependencies: ${{ parameters.dependencies }}
          templateVersion: 1.1.4-SNAPSHOT
            
    - id: directory-rename
      name: Renaming Files for Template
      action: fs:rename
      input:
        files:
          - from: ./${{parameters.name}}/src/main/java/com/triplelift/TEMPLATE_API
            to: ./${{parameters.name}}/src/main/java/com/triplelift/${{parameters.name | replace("-", "_")}}
          - from: ./${{parameters.name}}/src/test/java/com/triplelift/TEMPLATE_API
            to: ./${{parameters.name}}/src/test/java/com/triplelift/${{parameters.name | replace("-", "_")}}
          - from: ./${{parameters.name}}/src/it/java/com/triplelift/TEMPLATE_API
            to: ./${{parameters.name}}/src/it/java/com/triplelift/${{parameters.name | replace("-", "_")}}

    - id: delete-files-sdk-publishing
      if: ${{ "sdk_publishing" not in parameters.dependencies }}
      name: Delete Files Associated with GraphQL Code Generator
      action: fs:delete
      input:
        files:
          - ${{parameters.name}}/${{parameters.name}}-sdk
          - .github/workflows/publish-sdk.yml
          - ${{parameters.name}}/package.json
          - ${{parameters.name}}/codegen.yml
          - ${{parameters.name}}/package-lock.json
          - ${{parameters.name}}/yarn.lock

    - id: delete-flyway-migrate-files
      if: ${{ "flyway_migrate_files" not in parameters.dependencies }}
      name: Delete Files Associated with Flyway Migration
      action: fs:delete
      input:
        files:
          - .github/workflows/migrate-mysql-dev.yml
          - .github/workflows/migrate-mysql-prod.yml
          - db-migrations
          
    - id: cc-create
      name: Add Service to Code Climate Quality
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/api/proxy/codeclimate/scaffolder/v1/orgs/6217a5d89f71b400e0003168/repos'
        headers:
          content-type: 'application/json'
        body:
          data:
            type: 'repos'
            attributes:
              url: ${{ steps.publish.output.remoteUrl.slice(0, -4) }}

    - id: publish
      name: Publish Repo to GitHub
      action: publish:github
      input:
        allowedHosts: [ 'github.com' ]
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: 'internal'
        defaultBranch: 'develop'
        collaborators:
          - team: 'engineering'
            access: 'maintain'
          - team: ${{ parameters.owner }}
            access: 'admin'

    - id: register
      name: Register Service to Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
