name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0

      - name: Output release tag
        run: echo ${{ steps.latest_release_info.outputs.tag_name }}

      - uses: ./
        with: 
          version: ${{ github.event.release.tag_name }}
