name: Test

on:
  pull_request:
    types: [opened]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: info
      uses: konveyor/get-release-info@v1
      with:
        owner: "anestor6"
        repo: "self-service-action"

    - name: Print Release
      run: echo '${{ steps.info.outputs.release_info }}'
    

    - uses: actions/checkout@v2
    - uses: ./
      with: 
        version: ${{ steps.info.outputs.release_info }}
